ors/urls.py
from django.contrib import admin
from django.urls import path
from orders.views import order_list, order_create
urlpatterns = [
    path('', order_list, name='order_list'),
    path('admin/', admin.site.urls),
    path('order/', order_create, name='create_order'),
]

orders/models.py
from django.db import models
from django.core.validators import MinValueValidator
import decimal

class Customer(models.Model):
    username = models.CharField(max_length=150, unique=True)
    name = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=12, blank=True, default="")
    address = models.TextField(blank=True, default="")

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150)
    code = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    features = models.TextField()
    inventory = models.IntegerField()

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    discount_percentage = models.FloatField(blank=True, validators=[MinValueValidator(0.0)], default=0.0)


class OrderProducts(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(validators=[MinValueValidator(0)])
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

orders/forms.py
from django.forms.models import inlineformset_factory
from orders.models import Order, OrderProducts
from django import forms


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('amount', 'discount_amount', 'total',)


class OrderProductsForm(forms.ModelForm):
    class Meta:
        model = OrderProducts
        exclude = ('amount',)


OrderProductsFormset = inlineformset_factory(
    Order, OrderProducts, form=OrderProductsForm, extra=0,  can_delete=True)

orders/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from orders.models import *
from orders.forms import *
from django.urls import reverse
from django.db.models import Q
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.core import serializers
import json
import itertools
import decimal

# import openpyxl
# wb = openpyxl.load_workbook('products.xlsx')
# worksheet = wb["Sheet1"]
# excel_data = list()
# worksheet_iter = worksheet.iter_rows()
# next(worksheet_iter)
# for row in worksheet_iter:
#     row_data = list()
#     for cell in row:
#         if cell.value == None:
#             cell.value = 0.0
#         row_data.append(str(cell.value))
    # Product.objects.create(
    #     name=row_data[0],
    #     code=row_data[1],
    #     price=row_data[2],
    #     features=row_data[3],
    #     inventory=row_data[4]
    # )


def order_list(request):
    object_list = Order.objects.all()
    context = {'object_list': object_list}
    if request.is_ajax and request.GET:
        ajax_type = request.GET.get('ajax_type', None)
        if ajax_type == 'order_summery':
            id = request.GET.get('order_id', None)
            object = object_list.get(id=int(id))
            context = {'object': object}
            html = render_to_string('orders/order_summery.html', context)
        return HttpResponse(html, content_type="application/html")

    return render(request, 'orders/order_list.html', context)


def order_create(request):
    customer_obj = Customer.objects.all()
    product_objs = Product.objects.all()
    html = ''
    if request.is_ajax and request.GET:
        ajax_type = request.GET.get('ajax_type', None)
        if ajax_type == 'choose_price':
            product_id = request.GET.get('product_id', 'None')
            product_obj = product_objs.get(id=int(product_id))
            html = product_obj.price

        if ajax_type == 'get_user_data':
            customer_id = request.GET.get('customer_id', None)
            customer = customer_obj.get(id=int(customer_id))
            context = {'phone_number': customer.phone_number, 'address': customer.address}
            html = render_to_string('orders/edit_user_details.html', context)

        if ajax_type == 'save_user_data':
            customer_id = request.GET.get('customer_id', None)
            customer = customer_obj.get(id=int(customer_id))
            customer.phone_number = request.GET.get('phone_number', None)
            customer.address = request.GET.get('address', None)
            customer.save()
            context = {'phone_number': customer.phone_number, 'address': customer.address}
            html = render_to_string('orders/edit_user_details.html', context)

        if ajax_type == 'customer':
            search_text = request.GET.get('search_text', None)
            objects = customer_obj.filter(Q(name__contains=search_text) | Q(phone_number__contains=search_text))
            context = {'objects': objects}
            html = render_to_string('orders/option_list.html', context)

        if ajax_type == 'product':
            search_text = request.GET.get('search_text', None)
            objects = product_objs.filter(Q(name__contains=search_text) | Q(features__contains=search_text)| Q(code__contains=search_text))
            context = {'objects': objects}
            html = render_to_string('orders/option_list.html', context)

        return HttpResponse(html, content_type="application/html")

    if request.POST:
        form = OrderForm(request.POST)
        order_products = OrderProductsFormset(request.POST)
        if form.is_valid() and order_products.is_valid():
            order_instance = form.save()
            order_products.instance = order_instance
            order_obj = order_products.save()
            amount = 0
            for obj in order_obj:
                product = obj.product
                product_amount = obj.quantity * obj.product.price
                amount = amount + product_amount
                product.inventory = product.inventory - obj.quantity
                product.save()
                obj.amount = product_amount
                obj.save()
            order_instance.amount = amount
            discount_amount = amount*decimal.Decimal(order_instance.discount_percentage/100)
            order_instance.discount_amount = discount_amount
            order_instance.total = round(amount-discount_amount, 2)
            order_instance.save()
            return redirect('create_order')
        else:
            print(form.errors)
            print(order_products.errors)
    else:
        form = OrderForm()
        order_products = OrderProductsFormset()
    return render(request, 'orders/create_order.html', {'form': form, 'order_products': order_products})

orders/templates/orders/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0,minimal-ui">

    <title>Orders Taking System</title>

    <meta content="" name="description">
    <meta content="" name="author">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- jvectormap -->
    <link href="{% static 'orders/plugins/fullcalendar/vanillaCalendar.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'orders/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'orders/css/icons.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'orders/css/style.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- include summernote css/js -->
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

</head>
<style>
    .fa-edit {
    font-size: 21px;
    color: green;
}
b {
    font-weight: 700 !important;
}
.fa-trash{
    font-size: 21px;
    color: Red;
}
.main-heading{

    background-color: #e4e9d9;
}
</style>
<body>

{% block content %}
{% endblock content%}
    <script src="{% static 'orders/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <!-- App js -->
{% block javascript %}
{% endblock javascript %}
</body>
</html>

orders/templates/orders/create_order.html
{% extends 'orders/base.html' %}
{% load static %}
{% block content %}
{% load mytemplates %}
{% load formset_tags %}
<style>
    .add-row {
    color: green;
    font-weight: bold;
}

.delete-row {
    color: red;
    font-weight: bolder;
}
.form-control{
min-width:200px;

}
input[type="checkbox"] {
    min-width: 0px;
    height: 20px;
    margin-top: 9px;

}


#id_Approved{

        width: 32px;
    height: 23px;


}

.table {
    margin-bottom: -4px;
    margin-top: 30px;
}
</style>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="{% static 'orders/js/jquery.formset.js' %}"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

</head>
    <!-- End Navigation Bar-->
    <div class="clearfix"></div>
    <div class="wrapper">
        <div class="container-fluid mt-5">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-8 m-auto">
                    <div class="page-title-box">
                        <div class="btn-group pull-right">
                            <ol class="breadcrumb hide-phone p-0 m-0">
                                <li class="breadcrumb-item"><a href="#">Order</a></li>
                                <li class="breadcrumb-item active">Create</li>
                            </ol>
                        </div>
                        <h4 class="page-title">New Order</h4></div>
                </div>
            </div>
            <!-- end page title end breadcrumb -->
            <div class="row">
                <div class="col-10 m-auto">
                    <div class="card">
                        <div class="card-body">
                            <div></div>






                           <form action="" method="post" enctype="multipart/form-data" id="order_form">
                               {% csrf_token %}
                           {% for f in form%}

                               <div class="form-group mb-4 dapartment-details">

                               <label class="mb-2 pb-1">{{f.label}}{% if f.label == 'Customer' %}
                                    <a id="edit_customer" class="add-row" href="javascript:void(0)" hidden>Edit Customer</a>
                                   {% endif %}</label>
                                    {{f|add_attr:'class=form-control'}}
                               </div>

                               {% endfor %}

                                {% if form.errors %}

                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <div class="alert alert-danger">
                                                <strong>{{ error|escape }}</strong>
                                            </div>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endif %}



            <div style="overflow-x:auto" id="order_products" data-formset-prefix="{{ order_products.prefix }}">
            <table class="table" id="product_table" data-formset-body>
                {{ order_products.management_form }}
                     <thead style="background: #2831791f;">
                        <tr>
                                <th>Product</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Delete</th>

                        </tr>
                     </thead>
            </table>



                <script type="form-template" data-formset-empty-form>
                    {% escapescript %}
                    <tr class="{% cycle row1 row2 %}" data-formset-form>
                         {% for hidden in order_products.hidden_fields %}
                                {{ hidden }}
                        {% endfor %}


                        {% for field in order_products.empty_form.visible_fields %}
                            {% if not forloop.last %}
                                {% if forloop.first %}
                                    <td>
                                        {{ field|add_attr:'class=form-control product select2, required=true' }}
                                    </td>
                                    <td class="price">
                                        <input type="text" class="form-control product" readonly>
                                    </td>
                                {% else %}
                                    <td>
                                        {{ field|add_attr:'class=form-control product, required=true' }}
                                    </td>
                                {% endif %}


                            {% else %}

                                <td >
                                    <input type="checkbox" class="form-control delete" id="hu" onclick="removethis(this)">
                                </td>
                            {% endif %}

                        {% endfor %}

                    </tr>
            {% endescapescript %}
        </script>

        <!-- This button will add a new form when clicked -->
        <div style="margin-top: 20px;">
            <a class="add-row" href="javascript:void(0)" data-formset-add>+Add Product</a>
        </div>
        <script>
        jQuery(function($) {
            $("#order_products").formset({
                animateForms: true,
            });
        });
        </script>

            </div>
                                <div class="text-center m-t-15">
                                    <button type="submit" id="confirm_order" value="confirm_btn" class="btn btn-primary waves-effect waves-light submit_btn">Confirm</button>
                                </div>



<!--                          The Model popup to show Order summary      -->
                                <div id="myModal" class="modal fade" role="dialog">
                                  <div class="modal-dialog">
                                      <div class="modal-content" style="width: 144%;margin-left: -47px;">
                                      <div class="modal-header">
                                          <h1>Order Summery </h1>
                                      </div>
                                      <div class="modal-body">
                                        <div class="row">
                                          <div class="col-lg-12" id="order_summery">
                                                <table class="table">
                                                    <tr>
                                                        <th>Customer Name</th>
                                                        <th>:</th>
                                                        <th id="customer_name"></th>
                                                    </tr>
                                                </table>
                                              <table id="order_summary_table" class="table">
                                                  <tr style="background: #2831791f;">
                                                      <td> Product Name</td>
                                                      <td> price </td>
                                                      <td></td>
                                                      <td> Quantity </td>
                                                      <td>Total</td>
                                                  </tr>
                                              </table>
                                              <div id="amount_data" style="margin: 25px 10px;float: right;">

                                              </div>
                                          </div>
                                            <div style="margin-left: 35%;margin-bottom: 10%;">

                                            <button id="submit_order" type="submit" class="btn btn-raised btn-primary waves-effect submit_btn">Submit</button>
                                            <button  type="button" class="btn btn-raised btn-primary waves-effect" onclick="close()" id="model_button" style="margin-left:20px">Close</button>


                                            </div>

                                        </div>

                                      </div>

                                    </div>

                                  </div>
                                </div>

                        <!--End of Model Pop up-->

                            </form>

                        </div>
                    </div>
                    <!--end card-->
                </div>
                <!--end col-->
            </div>
            <!-- end row -->

        </div>
        <!-- end container -->
    </div>

<!--Model POPup-->

<!--                          The Model popup to Edit Customer      -->
                                <div id="customer_edit" class="modal fade" role="dialog">
                                  <div class="modal-dialog">
                                      <div class="modal-content" style="width: 144%;margin-left: -47px;">
                                           <div class="modal-header">
                                            </div>
                                      <div class="modal-body">
                                        <div class="row" id="customer_details">

                                        </div>

                                        <button id="save_edit" type="button" class="btn btn-raised btn-primary waves-effect submit_btn">Submit</button>
                                        <button  type="button" class="btn btn-raised btn-primary waves-effect" onclick="close()"  style="margin-left:20px">Close</button>

                                      </div>

                                    </div>

                                  </div>
                                </div>
                        <!--End of Customer Editing Pop up-->
{% endblock content %}
{% block javascript %}
    <!-- Dropzone js -->
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="{% static 'orders/js/custom.js' %}"></script>

{% endblock javascript %}

orders/templates/orders/edit_user_details.html
                                          <div class="col-lg-12">
                                                <div class="form-group mb-4 dapartment-details">

                                            <label class="mb-2 pb-1">Phone Number</label>
                                                    <input type="text" class="form-control" id="phone_number" value="{{phone_number}}">
                                                    <label class="mb-2 pb-1">Address</label>
                                                    <textarea class="form-control" id="address">{{address}}</textarea>
                                                </div>
                                          </div>

orders/templates/orders/option_list.html
{% for obj in objects %}
<option>{{obj}}</option>
{% endfor %}

orders/templates/orders/order_list.html
{% extends 'orders/base.html' %}
{% load static %}
{% block content %}
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
            <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>

 <div class="clearfix"></div>
    <div class="wrapper" id="wrapper">
        <div class="container-fluid mt-5">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-8 m-auto">
                    <div class="page-title-box">
                        <div class="btn-group pull-right">
                            <ol class="breadcrumb hide-phone p-0 m-0">
                                <li class="breadcrumb-item"><a href="#">Order</a></li>
                                <li class="breadcrumb-item active">Summery</li>
                            </ol>
                        </div>
                        <h4 class="page-title">Order Summery</h4></div>
                       <a style="color:green;font-size: 14px;margin-left: 15px;" class="add-row" href="{% url 'create_order' %}" >+ Add New</a>

                </div>
            </div>
            <!-- end page title end breadcrumb -->
            <div class="row">
                <div class="col-8 m-auto">
                    <div class="card">
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead class="main-heading">
                                    <tr>
                                        <th>SI.No</th>
                                        <th>Order</th>
                                    </tr>
                                </thead>
                                <tbody>

                                {% for object in object_list %}
                                    <tr style="cursor: pointer;" onclick="order_summer({{object.id}})">
                                        <th scope="row">{{forloop.counter}}</th>
                                        <td>{{object.customer}}</td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!--end card-->
                </div>
                <!--end col-->
            </div>
            <!-- end row -->

        </div>
        <!-- end container -->
    </div>
    <!-- end wrapper -->
    <!-- Footer -->

<!--                          The Model popup to show Order summary      -->
<div id="myModal" class="modal fade" role="dialog">

</div>



{% endblock content %}

{% block javascript %}
<script>

    function order_summer(id){
                       $.ajax({
                        data: {'ajax_type':'order_summery', 'order_id':id},
                        type: "GET",
                        dataType: "html",
                        url: this.url,
                        success: function(response) {
                        $("#myModal").html(response)
                        $("#myModal").modal({
                          backdrop: 'static',
                          keyboard: false,
                          show: true });
                        },
                        error: function(e, x, r) {
                           alert("error");
                        }
                    });

    }


    $(document).on("click", '#model_button', function () {
            $('#myModal').modal('toggle');
    });


</script>
{% endblock javascript %}

orders/templates/orders/order_summery.html
                                  <div class="modal-dialog">
                                      <div class="modal-content" style="width: 144%;margin-left: -47px;">
                                      <div class="modal-header">
                                          <h1>Order Summery </h1>
                                      </div>
                                      <div class="modal-body">
                                        <div class="row">
                                          <div class="col-lg-12" id="order_summery">
                                                <table class="table">
                                                    <tr>
                                                        <th>Customer Name</th>
                                                        <th>:</th>
                                                        <th id="customer_name">{{object.customer}}</th>
                                                    </tr>
                                                </table>
                                              <table id="order_summary_table" class="table">
                                                  <tr style="background: #2831791f;">
                                                      <td> Product Name</td>
                                                      <td> price </td>
                                                      <td></td>
                                                      <td> Quantity </td>
                                                      <td>Total</td>
                                                  </tr>

                                                  {% for obj in object.orderproducts_set.all %}
                                                  <tr>
                                                      <td>{{obj.product}}</td>
                                                      <td>{{obj.product.price}}</td>
                                                      <td>*</td>
                                                      <td>{{obj.quantity}}</td>
                                                      <td>{{obj.amount}}</td>
                                                  </tr>
                                                  {% endfor %}

                                              </table>
                                              <div id="amount_data" style="margin: 25px 10px;float: right;">

                                                                   <p> Amount = {{object.amount}} </p>
                                                                   <p>Discount = {{object.discount_amount}} (% {{object.discount_percentage}})</p>
                                                                   <p>Total = {{object.total}}</p>

                                              </div>
                                          </div>
                                            <div style="margin-left: 35%;margin-bottom: 10%;">
                                            <button  type="button" class="btn btn-raised btn-primary waves-effect"  id="model_button" style="margin-left:20px">Close</button>
                                            </div>

                                        </div>

                                      </div>

                                    </div>

                                  </div>

                        <!--End of Model Pop up-->